allowBuilds:
  '@apollo/protobufjs': true
  '@parcel/watcher': true
  '@prisma/engines': true
  '@scarf/scarf': true
  bcrypt: true
  esbuild: true
  prisma: true
  unrs-resolver: true
onlyBuiltDependencies:
  - '@apollo/protobufjs'
  - '@parcel/watcher'
  - '@prisma/client'
  - '@prisma/engines'
  - bcrypt
  - esbuild
  - prisma
  - unrs-resolver
